MI: true
backbone: resnet50
base_lr: 0.007
batch_size: 16
beta: false
crop_size: 513
dataset: CIFAR-100
embedding_size: 256
epochs: 50
exp: bn_lr7e-3
factor: ''
freeze_bn: false
gpu: 0
groups: null
infer: true
infer_params:
  model_filename: ''
  model_name: ''
  process_type: ''
last_mult: 1.0
mode: infer
model: ''
model_number: 1
model_type: scratch
n_layer: 12
n_skip_l: 3
resume: null
weight_std: false
workers: 4
